### PR TITLE
Create Skycoin Team.es.md

### PR DESCRIPTION
**Pull request by Palvini**

### CODE REVIEW

**Comment by 00glm** [comment]
It's good.
Just change 'Marketing' for 'Mercadotecnia'

**Comment by Palvini** [comment]
Done!

**Comment by Murlocvici** [comment]
Good job, Palvin

**Comment by gz-c** [comment]
The file needs to be in the same folder as the english version of the file

**Comment by Palvini** [comment]
fixed

**Comment by gz-c** [comment]
3 sky

**Pull request merged**
