### PR TITLE
3 topics were translated into Russian

### PR DESCRIPTION
**Pull request by Vittiv**

### CODE REVIEW

**Comment by rieneuf** [comment]
I think it worth to redirect to russian wikipedia articles if they exist. 

https://ru.wikipedia.org/wiki/%D0%94%D0%B2%D0%BE%D0%B9%D0%BD%D0%BE%D0%B5_%D1%80%D0%B0%D1%81%D1%85%D0%BE%D0%B4%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5 
https://ru.wikipedia.org/wiki/%D0%94%D0%BE%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D1%82%D0%B2%D0%BE_%D0%B4%D0%BE%D0%BB%D0%B8_%D0%B2%D0%BB%D0%B0%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F
ect

**Comment by gz-c** [comment]
@gogo-tattoo can you check these

**Comment by gogo-tattoo** [comment]
@gz-c There're some minor typos all over, but overall it's a very good work. We'd say accept it, then let the community fix typos :-)

**Comment by gz-c** [comment]
70 sky

**Pull request merged**
