### PR TITLE
Create Skycoin Distribution Event.fr.md

### PR DESCRIPTION
**Pull request by Nial25**
french translation by nial

### CODE REVIEW

**Comment by dsdallianz** [comment]
formatting at top of these needs to be as follows ("..." = fill in the blank) - this needs to be changed on all your current PRs:

++++
 +title = "..."
 +tags = [
 +    "...",
 +]
 +date = "..."
 +categories = [
 +    "...",
 +    "...",
 +]
 ++++

**Comment by dsdallianz** [comment]
formatting at top of these needs to be as follows ("..." = fill in the blank) - this needs to be changed on all your current PRs:

++++
+title = "..."
+tags = [

"...",
+]
+date = "..."
+categories = [
"...",
"...",
+]
++++

**Comment by Nial25** [comment]
I made the same way than the russian translation of https://github.com/skycoin/blog/blob/master/content/statement/Skycoin%20Bounty%20Program%201.ru.md
and https://github.com/skycoin/blog/blob/master/content/statement/Skycoin%20Distribution.ru.md

Also i followed I follow those indications https://mardanielm.wordpress.com/skycoin-contribute-to-blog-translation/ maybe it's showing a bad way.
I will make the correction

**Comment by Nial25** [comment]
Corrections applied

**Comment by gz-c** [comment]
5 sky

**Pull request merged**
