### PR TITLE
Create Skycoin Has Nothing To Do With Skynet.fr.md

### PR DESCRIPTION
**Pull request by Nial25**
french translation

### CODE REVIEW

**Comment by rieneuf** [comment]
It's fine

**Comment by Warmat** [comment]
Yes indeed

**Comment by dsdallianz** [comment]
This translation is worth 5 SKY, post sky addr here or pm me on telegram so I can send

**Comment by Nial25** [comment]
2bUj5HAnCpsNBimdF3NvhvJxs1p7ZgRcTfL
thx

**Pull request merged**
