### PR TITLE
Skycoin launches a vision for the new internet.de.md

### PR DESCRIPTION
**Pull request by Asgaror**
Added in brackets the technical english terms for
concensus-algorithm,
mesh networkink,
point-of-sale,
internet of things.

### CODE REVIEW

**Comment by gz-c** [comment]
continuation of #160

**Comment by Asgaror** [comment]
Added the spaces, thank you for reviewing.

**Comment by gz-c** [comment]
whats your sky addr

**Comment by Asgaror** [comment]
2aY1N6fyd5HN3fQXrW91Eveq2x69GpuQ1Qo

**Comment by gz-c** [comment]
4 sky

**Pull request merged**
