### PR TITLE
Skycoin Infographics

### PR DESCRIPTION
**Pull request by Levityss**
I hope this is right...

### CODE REVIEW

**Comment by gz-c** [comment]
```
ERROR 2018/01/22 15:36:04 failed to parse page metadata for "infographics/skycoin-digest-Stand-for.md": Near line 1 (last key parsed 'title'): expected value but found '“' instead
ERROR 2018/01/22 15:36:04 failed to parse page metadata for "infographics/skycoin-digest-FREE-internet.md": Near line 1 (last key parsed 'title'): expected value but found '“' instead
```

**Comment by gz-c** [comment]
It looks like you used special quote characters instead of "
Don't edit these files in microsoft word

**Comment by Levityss** [comment]
I used textwrangler and copied the md file that was in there. Weird. alright should I try again?

**Comment by Levityss** [comment]
I'm gonna retry this thing.

**Pull request closed without merging**
