### PR TITLE
Create Telegram Log - Whitepapers Slavery Anarchy.kr.md

### PR DESCRIPTION
**Pull request by coinyawong**
In progress

### CODE REVIEW

**Comment by coinyawong** [comment]
This translation was done.
And checked 3 times by myself.
It's ok.

**Comment by choisooho** [comment]
good job!

**Comment by woojumbs** [comment]
Every words are used properly!

**Comment by dsdallianz** [comment]
Post is worth 30 SKY, pm me your sky addr on telegram or post here to collect

**Pull request merged**
