### PR TITLE
Remove outdated statement: $40 transaction...

### PR DESCRIPTION
**Pull request by escapedcat**
>  * $40 transaction fees and climbing!  

This is not a valid statement (anymore). For example see:  https://bitcoinfees.info  
Since Segwit and Lightning are picking gaining tracktion fees are getting low (again).

### CODE REVIEW

**Comment by escapedcat** [comment]
Why isn't this a valid PR?

**Comment by gz-c** [comment]
Text matches the infographic

**Comment by escapedcat** [comment]
Well, then the infographic is wrong, isn't it?

**Comment by escapedcat** [comment]
I can create an issue for that if needed

**Comment by escapedcat** [comment]
https://github.com/skycoin/blog/issues/676  
Hope this helps.

**Pull request closed without merging**
