### PR TITLE
segwit2x.es.md

### PR DESCRIPTION
**Pull request by misucojocaur**
telegram user: misu cojocaur
*for bounty verification

### CODE REVIEW

**Comment by Senyoret1** [comment]
That post has already been translated and reviewed: https://github.com/skycoin/blog/pull/313

**Comment by misucojocaur** [comment]
ok, thanks, missed that one

**Comment by Senyoret1** [comment]
Please, in order to maintain order, follow the instructions. Only one file per pull requested and check which files have already been translated. https://github.com/skycoin/blog/files/1469162/github-translation-manual.pdf

**Comment by misucojocaur** [comment]
@Senyoret1 would you please review my other translations if you find the time? i also pulled up "state of the crypto market deveopment updates" and "skycoin-vs-ipfs", or i think i did lol

**Pull request closed without merging**
