### PR TITLE
add ru translation for Can Skycoin Be 51 Attacked.ru

### PR DESCRIPTION
**Pull request by VeronikaKhinevich**

### CODE REVIEW

**Comment by VeronikaKhinevich** [comment]
I have added one more translated article. Please check it too. 
Thank you in advance

**Comment by Licvid** [comment]
translations are ok.

**Comment by gz-c** [comment]
@Vittiv can you check these

**Comment by Vittiv** [comment]
Bad language, it looks like machine translation. I left my comments in russian Telegram channel.

**Pull request closed without merging**
