### PR TITLE
Skyledger: Blockchain’s Real Future.zh.md

### PR DESCRIPTION
**Pull request by weihuakevin**

### CODE REVIEW

**Comment by angryxueqiu** [comment]
@weihuakevin 
Checked, looks good to me :) 
I have some other pull request to be approved if you have spare time:
#380 #409 #412 #414  #419

**Comment by weihuakevin** [comment]
@angryxueqiu 加我微信吧weihua0719

**Comment by jayphbee** [comment]
Your translation is good, but you should according to the Markdown syntax, otherwise the displayed format on website is out of order.

**Comment by weihuakevin** [comment]
@jayphbee please check #410

**Pull request closed without merging**
