### PR TITLE
Skywire: The Next Internet (RU)

### PR DESCRIPTION
**Pull request by dmi3y**
Russian translation

### CODE REVIEW

**Comment by dmi3y** [comment]
Thanks @Vittiv Another correction, whenever it would be good to merge, I will squash commits in one.

**Comment by gz-c** [comment]
send sky address

**Comment by dmi3y** [comment]
Squashed commits in one

**Comment by dmi3y** [comment]
@gz-c 2UU3zRGhrYrAcPmoXrkiADpTTXaUtjQFpK7 please and thank you 🙏

**Comment by gz-c** [comment]
10 sky

**Comment by dmi3y** [comment]
Thanks @gz-c, you seemed to double send bounty, if that's not a tip. Let me know the address to send it back.

**Pull request merged**
