### PR TITLE
Create CX Overview.kr.md

### PR DESCRIPTION
**Pull request by coinyawong**
In progress.

### CODE REVIEW

**Comment by coinyawong** [comment]
This translation was done and checked 3 times.
I think it's perfect.
https://github.com/skycoin/blog/pull/143/commits/30429bb4012ce2735649b44825f26d0fbe017160

**Comment by woojumbs** [comment]
you did good job. i checked it 3 times only to find no error.lol. keep going!

**Comment by choisooho** [comment]
checked

**Comment by gz-c** [comment]
40 sky

**Pull request merged**
