### PR TITLE
Create Skywire - Skycoin Meshnet Project.kr.md

### PR DESCRIPTION
**Pull request by coinyawong**
Work in progress(translate to korean language)

### CODE REVIEW

**Comment by choisooho** [comment]
Good job!

**Comment by gz-c** [comment]
Need more checking because this article is difficult

**Comment by coinyawong** [comment]
I know your means. This article is so difficult and need high technology for understanding. But i'm web programmer(using java, jquery, db etc) and already checked this translation sufficiently.

**Comment by gz-c** [comment]
55 sky

**Pull request merged**
