### PR TITLE
Create Telegram Log - Whitepapers Slavery Anarchy.de.md

### PR DESCRIPTION
**Pull request by Asgaror**
First translation attempt.
I am not sure if it is demanded to translate titles like the 'Distributed Consensus Algorithm for Cryptocurrency Networks' or something rather simple like 'commit'. 
In my opinion these are universal terms that should be universally understood and cant be changed without changing the meaning of the statement but if it is mandatory to do so i'll be happy to make these improvements.

### CODE REVIEW

**Comment by gz-c** [comment]
30 sky once accepted

**Comment by Asgaror** [comment]
Revisited this pull request. Unfortunately its on my master branch and thats why the commits and changed files are clogged up. Sorry about that. 

The translated file is stated in the title of the pull request, its 'Telegram Log - Whitepapers Slavery Anarchy'.
You can start reviewing by clicking on this link: [https://github.com/skycoin/blog/pull/160/files/448195b0a22241a66b1d0b79ddb9b7185bfc7d4c..8dda0447f3e1c31a424b74dbc645082fcc7a5458](url)

Thanks in advance and sorry for the inconvenience.

**Comment by gz-c** [comment]
We can't merge this with the commits all like that

**Comment by Asgaror** [comment]
Alright, i'll close this one and open another. Since i made this translation before the bounties were changed, the 30 sky from above are still valid ?

**Comment by Asgaror** [comment]
Cleaned it up.

**Comment by gz-c** [comment]
Yes the 30 sky is still valid, I left that note to remember
This still needs a german reviewer though?

**Comment by M3GH** [comment]
some suggestions for correction for lines 0 to 100: 
15: Komma nach Hey
17: "ich" anstelle von Ich
31: Komma vor "um.. zu.."
48: Komma wegen Halbsatz-Nebensatz
56: "ihn" statt "ihm"
87: Ggf. "Koautor" anstelle von "Ko-Autor" (ist geläufiger)
97: Ggf. Komma nach "ich denke", zwecks Gliederungsstruktur. War notwendig nach alter Rechtschreibung.
101: Komma zwischen "prüfen mit", da Hauptsatz-Nebensatz.

**Pull request closed without merging**
